### ISSUE TITLE
Cannot find rules when npm linked

### ISSUE THREAD

**Issue by ianshward** [mapbox/lambda-cfn#23]
When you're developing on lambda-cfn or related, and you `npm link` lambda-cfn into a patrol stack, rules paths cannot be resolved because the wrong application root is used.

@zmully I believe the start of the problem is here https://github.com/mapbox/lambda-cfn/blob/7e278324d7fe52973f4315b5c9fa65e91f5f0310/lib/lambda-cfn.js#L59 which uses app-root-path here https://github.com/mapbox/lambda-cfn/blob/7e278324d7fe52973f4315b5c9fa65e91f5f0310/lib/lambda-cfn.js#L5 to resolve the root of the application.

There are a few places in lambda-cfn.js that rely on app-root-path.  There should be tests to ensure all these cases are handled properly, in addition to properly handling the case around an npm linked copy of lambda-cfn.

**Comment by zmully** [comment]
Looks like `export LAMBDA_TASK_ROOT=/patrol/service/root` fixes the app root path.

**Comment by zmully** [comment]
Updated the patrol docs to reflect this setting. While this works for deploying a patrol stack with a dev lambda-cfn, it breaks lambda-cfn tests. I don't think this is a deal breaker ATM, so it's left as an exercise for the reader to unset it before running any tests.
