### ISSUE TITLE
Update to Node v4

### ISSUE THREAD

**Issue by zmully** [mapbox/lambda-cfn#27]
AWS Lambda console now displays this warning in the console:

![screenshot_2016-04-14_16-48-23](https://cloud.githubusercontent.com/assets/10401798/14543163/c93a6204-0260-11e6-86b1-543e9615d7d4.png)

**Comment by zmully** [comment]
This will need to wait until CFN supports node 4:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html

This should be added by the end of May according to AWS support.

**Comment by zmully** [comment]
Node 4 now supported with the resource type `nodejs4.3`

**Comment by alulsh** [comment]
We should make the Node runtime version configurable as an option in the `module.exports.config` of a lambda-cfn function.

This will make it easier to specify creating Node 4 or Node 6 functions with lambda-cfn during the transition period when AWS Lambda supports both. It will make all future Node runtimes upgrade in AWS Lambda easier.

**Comment by alulsh** [comment]
Fixed in https://github.com/mapbox/lambda-cfn/pull/41 and the new [v0.1.5 release](https://github.com/mapbox/lambda-cfn/releases/tag/v0.1.5).
