### ISSUE TITLE
API GW Deployments immutable and do not update

### ISSUE THREAD

**Issue by zmully** [mapbox/lambda-cfn#37]
Quirk of API GW and CFN, since deployments are immutable, a new deployment has to be created every time the stack is updated for the latest methods to be deployed. This can be hacked around by randomizing the deployment name. #36

**Comment by ianshward** [comment]
@zmully you fixed this completely via #36 right?

**Comment by zmully** [comment]
Yes fixed by #36, unless you're seeing issues with a deployment.

**Comment by ianshward** [comment]
Great, not seeing any issues.  Going to close
