### ISSUE TITLE
Add helper to generate namespaced params

### ISSUE THREAD

**Issue by rodowi** [mapbox/lambda-cfn#39]
We need to provide a helper function to generate the namespaced parameter name so it can be used as a statement reference.

See https://github.com/mapbox/patrol-rules-aws/pull/80

``` js
  parameters: {
    deviceHistory: {
      Type: 'String',
      Description: 'ARN of S3 bucket for storing a list of known devices'
    }
  },
  statements: [
    {
      Effect: 'Allow',
      Action: [
        's3:GetObject',
        's3:ListBucket',
        's3:PutObject'
      ],
      Resource: { Ref: 'deviceHistory' }
    }
  ],
```

_Ref to deviceHistory will not work in this case_

cc: @zmully

**Comment by zmully** [comment]
Variables no longer namespaced in lamdba-cfn v2.
