### ISSUE TITLE
`init` command for new rules

### ISSUE THREAD

**Issue by zmully** [mapbox/lambda-cfn#45]
As part of the lambda-cfn refactor to 1 rule 1 stack, a convenience function for new rules should initialize and create skeleton files to speed rule development.

Let's keep this super simple for this first go round, the command should assume you're writing a new CloudWatch Event based rule.

`lambda-cfn init <rulename>` should:
1. Be run from a top level parent directory, all rules will be sub directories of this directory
1. Check for a `package.json` in the parent directory, create it if necessary
1. Add/update `lambda-cfn` as dependency in the `package.json`
1. Check the rulename (no spaces, no underscores, anything else not legal in a Cloudformation stack name, must contain only letters, numbers, dashes and start with an alpha character. )
1. Check and create a sub directory for the rule `./<rulename>`
1. Create `function.js` and `function.template.js` file skeletons (contents TBD)

**Comment by alulsh** [comment]
Working on this in https://github.com/mapbox/lambda-cfn/pull/48.

**Comment by alulsh** [comment]
Completed in https://github.com/mapbox/lambda-cfn/pull/51
