### ISSUE TITLE
`deploy` command

### ISSUE THREAD

**Issue by zmully** [mapbox/lambda-cfn#46]
For the 1 rule 1 stack refactor, we're moving from one repository containing multiple rules and creating a single stack for all rules to one repository with multiple rules each which gets its own stack.

For the initial command, wrap `cfn-config` with sane defaults to create a stack for a single rule, so 

`~/patrol-rules-aws/rule$ lambda-cfn deploy <environment>`  would run cfn-config with sane defaults, like:

`cfn-config create rule-<production> function.template.js -n patrol-rules-aws -r us-east-1 -c cfn-config-${AWS_ACCOUNT_ID}-us-east-1 -k kmsKey​`

**Comment by alulsh** [comment]
Completed in https://github.com/mapbox/lambda-cfn/pull/51.
