### ISSUE TITLE
Refactor lambda-cfn to one rule one stack

### ISSUE THREAD

**Issue by zmully** [mapbox/lambda-cfn#47]
Currently Lambda-cfn support multiple rules, in multiple repositories in a single stack. This makes deployment and maintenance a headache as well as being a hinderance to new users. Moving to a one rule one stack architecture will simplify the lambda-cfn codebase as well as improve usability. 

- support existing lambda-cfn rule functionality
- split lambda code from the lambda Cloudformation template
   - `function.js`: contains the actual lambda function code
   - `function.template.js`: Cloudformation template

**Comment by alulsh** [comment]
Completed in https://github.com/mapbox/lambda-cfn/pull/51.
